# reusable-workflow.yml
name: Reusable Workflow

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  shared-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "Hello ${{ inputs.name }}" |
             echo $(cat data.txt)"
