name: Use Data from Repo1

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  get_data_and_create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Call Repo1 Reusable Workflow
        id: repo1
        uses: tech-organization-mame/githubtest/.github/workflows/export-file.yml@main

      - name: Check out Repo2
        uses: actions/checkout@v3

      - name: Update data file
        run: |
          echo "Data from Repo1: ${{ steps.repo1.outputs.data_content }}" > new_data.txt

          # コミット準備
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-data-branch
          git add new_data.txt
          git commit -m "Update data file from Repo1"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-data-branch
          title: "Update data from Repo1"
          body: "This pull request adds the latest data from Repo1 to new_data.txt."
          base: main
