name: Call Reusable Workflow and Use Output

on:
  workflow_dispatch:

jobs:
  # (A) 再利用可能ワークフローを呼び出すジョブ
  call-workflow:
    uses: tech-organization-mame/githubtest/.github/workflows/export-file.yml@main
    # ★ ここでは steps / outputs は一切定義しない

  # (B) 取得した出力を使うジョブ
  use-output:
    needs: call-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Show output
        run: |
          echo "Data is: ${{ needs.call-workflow.outputs.data_content }}"
